apiVersion: v1
kind: Service
metadata:
  name: hdfs-browser-svc-0
  labels:
    dep: hdfs-browser-svc-0
spec:
  type: NodePort
  ports:
    - name: hdfs-b
      port: 50070
      targetPort: 50070
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-down-svc-0
  labels:
    dep: hdfs-down-svc-0
spec:
  type: NodePort
  ports:
    - name: hdfs-d
      port: 50075
      targetPort: 50075
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-svc-0
  labels:
    dep: yarn-svc-0
spec:
  type: NodePort
  ports:
    - name: yarn
      port: 8088
      targetPort: 8088
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-node-svc-0
  labels:
    dep: yarn-node-svc-0
spec:
  type: NodePort
  ports:
    - name: yarn-node
      port: 8042
      targetPort: 8042
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-svc-0
  labels:
    dep: hbase-svc-0
spec:
  type: NodePort
  ports:
    - name: hbase
      port: 16010
      targetPort: 16010
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    dep: tomcat-svc
spec:
  type: NodePort
  ports:
    - name: tomcat
      port: 8080
      targetPort: 8080
      nodePort: 48725
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-0"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-down-svc-1
  labels:
    dep: hdfs-down-svc-1
spec:
  type: NodePort
  ports:
    - name: hdfs-d
      port: 50075
      targetPort: 50075
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-1"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-svc-1
  labels:
    dep: yarn-svc-1
spec:
  type: NodePort
  ports:
    - name: yarn
      port: 8088
      targetPort: 8088
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-1"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-node-svc-1
  labels:
    dep: yarn-node-svc-1
spec:
  type: NodePort
  ports:
    - name: yarn-node
      port: 8042
      targetPort: 8042
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-1"
---
apiVersion: v1
kind: Service
metadata:
  name: oozie-svc-1
  labels:
    dep: oozie-svc-1
spec:
  type: NodePort
  ports:
    - name: oozie
      port: 11000
      targetPort: 11000
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-1"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-browser-svc-2
  labels:
    dep: hdfs-browser-svc-2
spec:
  type: NodePort
  ports:
    - name: hdfs-browser
      port: 50070
      targetPort: 50070
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-down-svc-2
  labels:
    dep: hdfs-down-svc-2
spec:
  type: NodePort
  ports:
    - name: hdfs-down
      port: 50075
      targetPort: 50075
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-node-svc-2
  labels:
    dep: yarn-node-svc-2
spec:
  type: NodePort
  ports:
    - name: yarn-node
      port: 8042
      targetPort: 8042
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-history-svc-2
  labels:
    dep: yarn-history-svc-2
spec:
  type: NodePort
  ports:
    - name: yarn-history
      port: 19888
      targetPort: 19888
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-svc-2
  labels:
    dep: spark-history-svc-2
spec:
  type: NodePort
  ports:
    - name: spark-history
      port: 18080
      targetPort: 18080
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: flink-history-svc-2
  labels:
    dep: flink-history-svc-2
spec:
  type: NodePort
  ports:
    - name: flink-history
      port: 8082
      targetPort: 8082
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-svc-2
  labels:
    dep: hbase-svc-2
spec:
  type: NodePort
  ports:
    - name: hbase
      port: 16010
      targetPort: 16010
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Chart.Name }}-ss-2"
