apiVersion: v1
kind: ConfigMap
metadata:
  name: initsh
  namespace: {{ .Release.Namespace }}
data:
  initsh-config: |-
    #!/bin/bash
    source /etc/profile
    host_num=`echo $HOSTNAME | awk -F- '{print $NF}'`
    echo $host_num > /user/data/zookeeper/data/myid

    ssh root@hadoop-basic-ss-0.ha-svc.hadoop-basic.svc.cluster.local
    exec /usr/sbin/init
    