apiVersion: v1
kind: ConfigMap
metadata:
  name: initfstart
  namespace: {{ .Release.Namespace }}
data:
  initfstart-config: |-
    #!/bin/bash
    source /etc/profile
    case $1 in
      zkfc)
      zkCli.sh > /user/zk-status.txt <<EOF
        ls /
    EOF
      if [ `grep 'hadoop-ha' /user/zk-status.txt | wc -l` -eq 0 ];then
        hdfs zkfc -formatZK
      else
        echo 'zookeeper exsit'
      fi
      ;;

      nnfc)
      if [ ! -d /user/data/hadoop/hdfs/name ];then
        hadoop namenode -format
        ssh $2 "rm -rf /user/data/hadoop/hdfs"
        scp -r /user/data/hadoop/hdfs $2:/user/data/hadoop/
        sleep 5
      else
        echo 'nn exsit'
      fi
      ;;

      flink)
      hadoop fs -test -e hdfs://ns/flink/history ; 
      if [ $? -ne 0 ]; then 
        hadoop fs -mkdir -p hdfs://ns/flink/history ;
        sleep 5
      else
        echo 'flink exsit'
      fi
      ;;

      oozie)
      hadoop fs -test -e /user/root/share/lib/* ;
      if [ $? -ne 0 ]; then  
        (oozie-setup.sh prepare-war sharelib create -fs hdfs://ns -locallib $OOZIE_HOME/oozie-sharelib-4.0.0-cdh5.3.6-yarn.tar.gz) && (ooziedb.sh create -sqlfile oozie.sql -run DB Connection && oozied.sh start);
        sleep 5
      else
        oozied.sh start
        echo 'oozie exsit'
      fi
      ;;

      spark)
      hadoop fs -test -e hdfs://ns/log/spark/eventlogs ;
      if [ $? -ne 0 ]; then 
        hadoop fs -mkdir -p hdfs://ns/log/spark/eventlogs && hadoop fs -mkdir -p hdfs://ns/spark_jars/ && hadoop fs -put $SPARK_HOME/jars/*  hdfs://ns/spark_jars/;
        sleep 5
      else
        echo 'spark exsit'
      fi
      ;;

      *)
        echo 'other'
      ;;
    esac


