apiVersion: v1
kind: ConfigMap
metadata:
  name: initsh
  namespace: {{ .Release.Namespace }}
data:
  initsh-config: |-
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    #!/bin/bash
    source /etc/profile
    host_num=`echo $HOSTNAME | awk -F- '{print $NF}'`
    echo $host_num > /user/data/zookeeper/data/myid
    touch /user/nodeinfo/nodenum
    if [ `sed -n '/HADOOP_NUM=/p' /user/nodeinfo/nodenum |awk -F= '{print $2}'` -lt $host_num ];then sed -i '/ENV_HADOOP_NUM=/d' /user/nodeinfo/nodenum;echo "HADOOP_NUM=$host_num" >> /user/nodeinfo/nodenum;else echo "RESTART_NODE=$host_num" >> /user/nodeinfo/nodenum; fi
    
    exec /usr/sbin/init
