apiVersion: v1
kind: ConfigMap
metadata:
  name: initsh
  namespace: {{ .Release.Namespace }}
data:
  initsh-config: |-
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    #!/bin/bash
    source /etc/profile
    host_num=`echo $HOSTNAME | awk -F- '{print $NF}'`
    echo $host_num > /user/data/zookeeper/data/myid
    
    exec /usr/sbin/init
    