apiVersion: v1
kind: ConfigMap
metadata:
  name: inittestsh
  namespace: {{ .Release.Namespace }}
data:
  inittestsh-config: |-
    #!/bin/bash
    touch /user/b.txt
    echo `date` >> /user/b.txt
    
