apiVersion: v1
kind: ConfigMap
metadata:
  name: initsh
  namespace: {{ .Release.Namespace }}
data:
  initsh-config: |-
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    #!/bin/bash
    source /etc/profile
    host_num=`echo $HOSTNAME | awk -F- '{print $NF}'`
    echo $host_num > /user/data/zookeeper/data/myid

    if [ $host_num -eq 0 ];then
      echo 'export ENV_HADOOP_NUM=0' >> /etc/profile
    else
      until [ `ping -c 1 {{ $chartName }}-ss-0.ha-svc.{{ $namespace }}.svc.cluster.local | grep ', 0% packet loss,' | wc -l` = 1  ]
      do
        sleep 3
        echo "等待DNS服务"
      done
      ssh root@{{ $chartName }}-ss-0.ha-svc.{{ $namespace }}.svc.cluster.local "echo \`sed -n '/export ENV_HADOOP_NUM/p' /etc/profile | awk -F= '{print $2}'\` >> /etc/profile ;if [ \`sed -n '/export ENV_HADOOP_NUM/p' /etc/profile | awk -F= '{print $2}'\` -lt "$host_num" ];then sed -i '/export ENV_HADOOP_NUM=/d' /etc/profile; echo 'export ENV_HADOOP_NUM="$host_num"' >> /etc/profile;else echo 'export ENV_HADOOP_NUM=111"$host_num"' >> /etc/profile; fi"
    fi
    
    exec /usr/sbin/init
    