apiVersion: v1
kind: ConfigMap
metadata:
  name: restartsh
  namespace: {{ .Release.Namespace }}
data:
  restart-config: |-
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    #!/bin/bash
    


