apiVersion: v1
kind: ConfigMap
metadata:
  name: initsh
  namespace: {{ .Release.Namespace }}
data:
  initsh-config: |-
    #!/bin/bash
    source /user/apps/hadoop2-etcprofile.sh
    host_num=`echo $HOSTNAME | awk -F- '{print $NF}'`
    echo $host_num > /user/data/zookeeper/data/myid 
    exec /usr/sbin/init 
    