apiVersion: v1
kind: ConfigMap
metadata:
  name: slaves
  namespace: {{ .Release.Namespace }}
data:
  slaves-config: |-
    {{- $app_namespace_bak := .Values.global.app_namespace_bak }}
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    {{- range .Values.volumenum}}
    {{ $chartName }}-ss-{{ .num }}.ha-svc.{{ $namespace }}.svc.cluster.local
    {{- end }}