apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-site
  namespace: {{ .Release.Namespace }}
data:
  yarn-site-config: |-
    {{- $app_namespace_bak := .Values.global.app_namespace_bak }}
    {{- $chartName := .Chart.Name }}
    {{- $namespace := .Release.Namespace }}
    <?xml version="1.0"?>
    <!--
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License. See accompanying LICENSE file.
    -->
    <configuration>
      <property>  
          <name>yarn.nodemanager.vmem-check-enabled</name>  
          <value>false</value>  
      </property> 
      <property>
              <name>yarn.resourcemanager.ha.enabled</name>
              <value>true</value>
      </property>

      <property>
              <name>yarn.resourcemanager.recovery.enabled</name>
              <value>true</value>
      </property>

      <property>
              <name>yarn.resourcemanager.connect.retry-interval.ms</name>
              <value>2000</value>
      </property>

      <property>
              <name>yarn.resourcemanager.ha.automatic-failover.enabled</name>
              <value>true</value>
      </property>

        <property>
            <name>yarn.resourcemanager.cluster-id</name>
            <value>yrc</value>
      </property>

      <property>
            <name>yarn.resourcemanager.ha.rm-ids</name>
            <value>rm1,rm2</value>
      </property>

        <property>
            <name>yarn.resourcemanager.hostname.rm1</name>
            <value>{{ $chartName }}-ss-1.ha-svc.{{ .Release.Namespace }}.svc.cluster.local</value>
        </property>

        <property>
            <name>yarn.resourcemanager.hostname.rm2</name>
            <value>{{ $chartName }}-ss-2.ha-svc.{{ .Release.Namespace }}.svc.cluster.local</value>
      </property>

        <property>
            <name>yarn.resourcemanager.webapp.address.rm1</name>
            <value>{{ $chartName }}-ss-1.ha-svc.{{ .Release.Namespace }}.svc.cluster.local:8088</value>
        </property>

        <property>
            <name>yarn.resourcemanager.webapp.address.rm2</name>
            <value>{{ $chartName }}-ss-2.ha-svc.{{ .Release.Namespace }}.svc.cluster.local:8088</value>
        </property>

          <property>
            <name>yarn.resourcemanager.zk-address</name>
            {{- $namespace := .Release.Namespace }}
            {{- $lastnodeindex := .Values.lastnodeindex|int}}
            {{ range $key, $val := .Values.volumenum }}
              {{- if eq $key 0}}
              {{- "<value>" }}{{ $chartName }}-ss-{{ .num }}.ha-svc.{{ $namespace }}.svc.cluster.local:2181,
              {{- else if and (gt $key 0) (lt $key $lastnodeindex) }}
              {{- "" }}{{ $chartName }}-ss-{{ .num }}.ha-svc.{{ $namespace }}.svc.cluster.local:2181,
              {{- else }}
              {{- "" }}{{ $chartName }}-ss-{{ .num }}.ha-svc.{{ $namespace }}.svc.cluster.local:2181</value>
              {{- end }}
            {{- end }}
        </property>

          <property>    
            <name>yarn.nodemanager.aux-services</name>    
            <value>mapreduce_shuffle</value>    
        </property> 

        <property>
            <name>yarn.nodemanager.pmem-check-enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>yarn.nodemanager.vmem-check-enabled</name>
            <value>false</value>
        </property>
        <property>
                <name>yarn.log-aggregation-enable</name>
                <value>true</value>
        </property>

        <property>
                <name>yarn.log-aggregation.retain-seconds</name>
                <value>86400</value>
        </property>

      <property>
              <name>yarn.log.server.url</name>
              <value>http://{{ $chartName }}-ss-0.ha-svc.{{ .Release.Namespace }}.svc.cluster.local:19888/jobhistory/logs/</value>
        </property>

        <property>
            <name>yarn.log-aggregation.retain-check-interval-seconds</name>
            <value>86400</value>
        </property> 

        
    </configuration>

