apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    svc: "{{ .Chart.Name }}-svc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.BasicConfig.ServicePort }}
      targetPort: mysql-port
      protocol: TCP
      name: http
      nodePort: 16833
  selector:
    app: "{{ .Chart.Name }}-pod"
