apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ if .Values.global.app_namespace_bak }}{{ .Chart.Name }}-pv-{{ .Release.Namespace }}-{{ .Values.global.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}{{ end }}
spec:
  capacity:
    storage: {{ .Values.BasicConfig.StorageCapacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ if .Values.global.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}-{{ .Values.global.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}{{ end }}
  nfs:
    {{- if .Values.global.app_namespace_bak }}
    path: {{ .Values.BasicConfig.StoragePath }}{{ .Release.Namespace }}/{{ .Values.global.app_namespace_bak }}/{{ .Chart.Name }}
    {{- else }}
    path: {{ .Values.BasicConfig.StoragePath }}{{ .Release.Namespace }}/{{ .Chart.Name }}
    {{- end }}
    server: {{ .Values.BasicConfig.StorageServer }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ if .Values.global.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}-{{ .Values.global.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}{{ end }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.BasicConfig.StorageCapacity }}
  storageClassName: {{ if .Values.global.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}-{{ .Values.global.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc-{{ .Release.Namespace }}{{ end }}
  